package ir.ac.iust.dml.kg.access.entities.enumerations

enum class MappingStatus {
  Mapped, NearlyMapped, NotMapped, Multiple, Translated, AutoGenerated;

  fun getPrecession() =
      when (this) {
        Mapped -> 1.0
        NearlyMapped -> 0.9
        NotMapped -> 0.6
        Multiple -> 0.3
        Translated -> 0.5
        AutoGenerated -> 0.1
        else -> 0.0
      }
}